baseURL      = "https://fabiolb.net/"
languageCode = "en-us"
title        = "fabio - The Consul Load-Balancer"
disableKinds = ["taxonomy"]
ignoreLogs   = ['warning-goldmark-raw-html']

[params]
  googleAnalytics = "UA-2812942-5"

